version: '3'
services:
  phpweb:
    container_name: starter-php
    build: .
    restart: always
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html/"
    command: php -S 0.0.0.0:80 -t ./public